### ISSUE TITLE
use of tinygizmo

### ISSUE THREAD

**Issue by ddiakopoulos** [cartman300/libTech#1]
Hi! I see you replaced your initial integration of tinygizmo with im3d. I'd be happy to understand what integration challenges or features that are missing from tinygizmo that drove the change :)

**Comment by cartman300** [comment]
Actually my first implementation was im3d, but i had some problems with it so i swapped to tinygizmo. Turned out i had the same problems with it too, which were in fact caused by the use of horizontal fov instead of vertical.

In the end i decided for im3d again because of some small minor bugs, from some angles scale gizmo seems to invert (as in, cursor movement to the left should be increasing the scale, but it's decreasing). And as mentioned in the readme, some anomalous output at some angles.

**Comment by ddiakopoulos** [comment]
thanks! this is very helpful feedback. good luck with your project :)
